---
- name: Create an empty file
  hosts: all
  become: yes
  tasks:
    - name:
      command:
        cmd: whoami
    - name: Ensure the file exists
      file:
        path: "/home/jenkins/emptyfile.txt"  # Specify the file path
        state: touch  # This will create an empty file if it doesn't exist
        mode: '0644'  # Set file permissions (optional)

    - name: create a directory
      file:
        path: "/home/jenkins/test"
        state: directory
        mode : 0755
