---
- name: Copy shell scirpt to remote machine
  hosts: all

  tasks:
  - name: copy shell scirpt
    copy:
      src: /home/pankaj/playbook/test.sh 
      dest: /home/pankaj/ansible-manifest
      mode: u=rwx

  - name: run copied shell script
    shell: /home/pankaj/ansible-manifest/test.sh >>test.log
    args:
      chdir: /home/pankaj/ansible-manifest/
      creates: test.log

  - name:
    debug: msg="file copied & run successfully"
      
